# Change these first
owner: UmbHost # Your GitHub organization or username, where this repository lives
repo: Status-Page # The name of this repository

sites:
  - name: UmbHost Website (UK)
    url: https://umbhost.net
  - name: UmbHost Website (US)
    url: https://us.umbhost.net
  - name: UmbHost Website (EU)
    url: https://eu.umbhost.net
  - name: UmbHost Website (AU)
    url: https://eu.umbhost.net
  - name: UmbHost Store
    url: https://my.umbhost.net/store
  - name: UmbCheckout Documentation
    url: https://docs.umbcheckout.net
  - name: UmbCheckout Demo
    url: https://demo.umbcheckout.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.umbhost.dev
  # baseUrl: /your-repo-name
  #baseUrl: /Status-Page
  name: UmbHost Limited
  logoUrl: https://umbhost.net/media/bckiw2jz/umbhost-logo-alt-strapline-white.svg
  favicon: https://umbhost.net/icons/favicon-32x32.png
  introTitle: "UmbHost Limited Status Page"
  introMessage: This is where you can see the Live status, planned maintenance and historical status for your services.
  navbar:
    - title: Status
      href: /
    - title: Knowledgebase
      href: https://my.umbhost.net/knowledgebase
    - title: Support Tickets
      href: https://my.umbhost.net/submitticket.php

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
